const REGIONS = [
  {
    id: 1,
    name: 'Starting Area',
    locations: ['Elm', 'Pokegear', 'Cherrygrove', 'Mr. Pokemon', 'Map Card', 'Mystic Water', 'Oak'],
    routes: [29, 30, 31],
    description: 'New Bark, Cherrygrove + Rts 29-31 (not Dark Cave, though)',
  },
  {
    id: 2,
    name: 'Violet',
    locations: [
      'Violet City',
      'Violet Mart',
      'Sprout Tower',
      'Rock Smash Guy',
      'Falkner',
      'Miracle Seed',
      'Old Rod Guru',
    ],
    routes: [32, 36],
    description: 'Violet + Rts 32, 36',
  },
  {
    id: 3,
    name: 'Alph Union',
    locations: ['Ruins of Alph', 'Union Cave'],
    routes: [],
    description: 'Ruins of Alph, Union Cave',
  },
  {
    id: 4,
    name: 'Azalea',
    locations: [
      'Azalea',
      'Ilex',
      'Slowpoke Well',
      'Kurt',
      'Bugsy',
      'Charcoal',
      'Headbutt Guy',
      "King's Rock",
      'Soft Sand',
      'Sweet Scent Girl',
    ],
    routes: [33, 34],
    description: 'Azalea, Ilex + Rts 33, 34',
  },
  {
    id: 5,
    name: 'Goldenrod',
    locations: [
      'Goldenrod',
      'National Park',
      'Underground Bargain',
      'Underground Herb',
      'Radio',
      'Bike Shop',
      'Buena',
      'Department Store Basement',
      'Flower Shop',
      'Kenya Gate',
      'Bug Catching',
      'Whitney',
      'Coin Case',
      'GS Ball',
    ],
    routes: [34, 35],
    description: 'Goldenrod, National Park + Rt 35',
  },
  {
    id: 6,
    name: 'Ecruteak',
    locations: [
      'Ecruteak',
      'Tin Tower',
      'Burned Tower',
      'Dance Theatre',
      'Itemfinder',
      'Morty',
      'Rainbow Wing',
    ],
    routes: [37],
    description: 'Ecruteak + Rt 37',
  },
  {
    id: 7,
    name: 'Olivine',
    locations: ['Olivine', 'SS Aqua', 'Good Rod Guru', 'Lighthouse', 'Jasmine'],
    routes: [38, 39, 40],
    description: 'Olivine, SS Aqua + Rts 38-40',
  },
  {
    id: 8,
    name: 'Cianwood',
    locations: ['Cianwood', 'Whirl Islands', 'Chuck', 'Secret Potion'],
    routes: [41],
    description: 'Cianwood, Whirl Islands + Rt 41',
  },
  {
    id: 9,
    name: 'Mt. Mortar',
    locations: ['Mt Mortar'],
    routes: [42],
    description: 'Mt. Mortar + Rt 42',
  },
  {
    id: 10,
    name: 'Mahogany',
    locations: ['Mahogany', 'Lake of Rage', 'Rocket Base', 'Pryce', 'Red Scale'],
    routes: [43],
    description: 'Mahogany, Lake of Rage + Rt 43',
  },
  {
    id: 11,
    name: 'Ice Path',
    locations: ['Ice Path'],
    routes: [44],
    description: 'Ice Path + Rt 44',
  },
  {
    id: 12,
    name: 'Blackthorn',
    locations: ['Blackthorn', 'Dark Cave', 'Clair', 'Dragons Den'],
    routes: [45, 46],
    description: 'Blackthorn, Dark Cave (both sides) + Rt 45, 46',
  },
  {
    id: 13,
    name: 'Central Kanto',
    locations: [
      'Cerulean',
      'Saffron',
      'Celadon',
      'Vermilion',
      'Copycat',
      'Dojo',
      'Erika',
      'Machine Part',
      'Bills Grandpa',
      'Mr Psychic',
      'Silph Co',
      'Underground Path',
    ],
    routes: [24, 25, 5, 17],
    description: 'Cerulean, Saffron, Celadon, Vermillion + Rts 24, 25, 5, 17',
  },
  {
    id: 14,
    name: 'Eastern Kanto',
    locations: [
      'Lavender',
      'Fuchsia',
      'Rock Tunnel',
      'Power Plant',
      'Super Rod Guru',
      'Janine',
      'Expansion Card',
    ],
    routes: [8, 9, 10, 11, 12, 13, 14, 15],
    description: 'Lavender, Fuchsia, Rock Tunnel, Power Plant + Rts 8-15',
  },
  {
    id: 15,
    name: 'Western Kanto',
    locations: [
      'Pewter',
      'Viridian',
      'Pallet',
      'Cinnabar',
      'Mt Moon',
      'Mount Moon',
      "Diglett's Cave",
      'Seafoam Islands',
      'Silver Wing',
    ],
    routes: [4, 2, 1],
    description: "Pewter, Viridian, Pallet, Cinnabar, Mt Moon, Diglett's Cave, Seafoam + Rts 1-4",
  },
  {
    id: 16,
    name: 'Victory Road',
    locations: ['Victory Road', 'Indigo Plateau', 'Mt. Silver', 'Tohjo Falls'],
    routes: [26, 27, 28],
    description: 'Victory Road, Indigo, Mt. Silver, Tohjo + Rts. 26-28',
  },
];

export const KOVOLTA_REGIONS = [
  {
    id: 1,
    name: 'Starting Area',
    locations: ['Players_House', 'Mr_Pokemons_House', 'Cherrygrove', 'Elms_Lab'],
    routes: [29, 30, 31],
    description: 'New Bark, Cherrygrove + Rts 29-31 (not Dark Cave, though)',
  },
  {
    id: 2,
    name: 'Violet',
    locations: ['Violet', 'Sprout_Tower'],
    routes: [32, 36],
    description: 'Violet + Rts 32, 36',
  },
  {
    id: 3,
    name: 'Alph Union',
    locations: ['Ruins_Of_Alph', 'Union_Cave'],
    routes: [],
    description: 'Ruins of Alph, Union Cave',
  },
  {
    id: 4,
    name: 'Azalea',
    locations: ['Azalea', 'Ilex_Forest', 'Slowpoke_Well', 'Charcoal_Kiln', 'Kurts_House'],
    routes: [33, 34],
    description: 'Azalea, Ilex + Rts 33, 34',
  },
  {
    id: 5,
    name: 'Goldenrod',
    locations: ['Goldenrod', 'Radio_Tower', 'National_Park'],
    routes: [34, 35],
    description: 'Goldenrod, National Park + Rt 35',
  },
  {
    id: 6,
    name: 'Ecruteak',
    locations: ['Ecruteak', 'Tin_Tower', 'Dance_Theater', 'Burned_Tower'],
    routes: [37],
    description: 'Ecruteak + Rt 37',
  },
  {
    id: 7,
    name: 'Olivine',
    locations: ['Olivine', 'Fast_Ship'],
    routes: [38, 39, 40],
    description: 'Olivine, SS Aqua + Rts 38-40',
  },
  {
    id: 8,
    name: 'Cianwood',
    locations: ['Cianwood', 'Whirl_Island'],
    routes: [41],
    description: 'Cianwood, Whirl Islands + Rt 41',
  },
  {
    id: 9,
    name: 'Mt. Mortar',
    locations: ['Mount_Mortar'],
    routes: [42],
    description: 'Mt. Mortar + Rt 42',
  },
  {
    id: 10,
    name: 'Mahogany',
    locations: ['Mahogany', 'Lake_Of_Rage', 'Team_Rocket_Base'],
    routes: [43],
    description: 'Mahogany, Lake of Rage + Rt 43',
  },
  {
    id: 11,
    name: 'Ice Path',
    locations: ['Ice_Path'],
    routes: [44],
    description: 'Ice Path + Rt 44',
  },
  {
    id: 12,
    name: 'Blackthorn',
    locations: ['Dragon_Shrine', 'Dark_Cave', 'Dragons_Den', 'Blackthorn'],
    routes: [45, 46],
    description: 'Blackthorn, Dark Cave (both sides) + Rt 45, 46',
  },
  {
    id: 13,
    name: 'Central Kanto',
    locations: ['Cerulean', 'Vermilion', 'Celadon', 'Saffron', 'Pokemon_Fan_Club', 'Copycats', 'Mr_Psychics', 'Fighting_Dojo', 'Underground_Path', 'Bills_House', 'Silph_Co'],
    routes: [24, 25, 5, 17],
    description: 'Cerulean, Saffron, Celadon, Vermillion + Rts 24, 25, 5, 17',
  },
  {
    id: 14,
    name: 'Eastern Kanto',
    locations: ['Fuchsia', 'Lav_Radio_Tower', 'Rock_Tunnel', 'Power_Plant', 'Lavender'],
    routes: [8, 9, 10, 11, 12, 13, 14, 15],
    description: 'Lavender, Fuchsia, Rock Tunnel, Power Plant + Rts 8-15',
  },
  {
    id: 15,
    name: 'Western Kanto',
    locations: ['Pewter', 'Seafoam_Gym', 'Viridian', 'Digletts_Cave', 'Mount_Moon', 'Cinnabar', 'Mt_Moon'],
    routes: [4, 2, 1],
    description: "Pewter, Viridian, Pallet, Cinnabar, Mt Moon, Diglett's Cave, Seafoam + Rts 1-4",
  },
  {
    id: 16,
    name: 'Victory Road',
    locations: ['Victory_Road', 'Tohjo_Falls', 'Silver_Cave', 'Indigo_Plateau'],
    routes: [26, 27, 28],
    description: 'Victory Road, Indigo, Mt. Silver, Tohjo + Rts. 26-28',
  },
];

export const regionColorClasses = [
  'black',
  'orange',
  'lt-blue',
  'yellow',
  'green',
  'dk-blue',
  'red',
  'pink',
];

export default REGIONS;
