// TODO? Should we get screenshots of each trainer and use pictures instead of text
const RIVALS = [
  { id: 1, name: 'Cherrygrove City - ???'},
  { id: 2, name: 'Route 30 - Youngster Joey'},
  { id: 3, name: 'Route 30 - Youngster Mikey'},
  { id: 4, name: 'Route 30 - Bug Catcher Don'},
  { id: 5, name: 'Route 31 - Bug Catcher Wade'},
  { id: 6, name: 'Sprout Tower - 2F - Sage Nico'},
  { id: 7, name: 'Sprout Tower - 1F - Sage Chow'},
  { id: 8, name: 'Sprout Tower - 2F - Sage Edmond'},
  { id: 9, name: 'Sprout Tower - 3F - Sage Neal'},
  { id: 10, name: 'Sprout Tower - 3F - Sage Troy'},
  { id: 11, name: 'Sprout Tower - 3F - Sage Li'},
  { id: 12, name: 'Violet City Gym - Bird Keeper Abe'},
  { id: 13, name: 'Violet City Gym - Bird Keeper Rod'},
  { id: 14, name: 'Violet City Gym - Gym Leader Falkner'},
  { id: 15, name: 'Route 32 - Youngster Albert'},
  { id: 16, name: 'Route 32 - Picnicker Liz'},
  { id: 17, name: 'Route 32 - Camper Roland'},
  { id: 18, name: 'Route 32 - Youngster Gordon'},
  { id: 19, name: 'Route 32 - Fisher Ralph'},
  { id: 20, name: 'Route 32 - Fisher Justin'},
  { id: 21, name: 'Route 32 - Fisher Henry'},
  { id: 22, name: 'Route 32 - Bird Keeper Peter'},
  { id: 23, name: 'Union Cave - 1F - Hiker Daniel'},
  { id: 24, name: 'Union Cave - 1F - Hiker Russel'},
  { id: 25, name: 'Union Cave - 1F - Firebreather Bill'},
  { id: 26, name: 'Union Cave - 1F - Pokemaniac Larry'},
  { id: 27, name: 'Union Cave - 1F - Firebreather Ray'},
  { id: 28, name: 'Route 33 - Hiker Anthony'},
  { id: 29, name: 'Slowpoke Well - B1F - Rocket Grunt #1'},
  { id: 30, name: 'Slowpoke Well - B1F - Rocket Grunt #2'},
  { id: 31, name: 'Slowpoke Well - B1F - Rocket Grunt #3'},
  { id: 32, name: 'Slowpoke Well - B1F - Rocket Grunt #4'},
  { id: 33, name: 'Azalea Town Gym - Twins Amy & May'},
  { id: 34, name: 'Azalea Town Gym - Bug Catcher Al'},
  { id: 35, name: 'Azalea Town Gym - Bug Catcher Benny'},
  { id: 36, name: 'Azalea Town Gym - Bug Catcher Josh'},
  { id: 37, name: 'Azalea Town Gym - Gym Leader Bugsy'},
  { id: 38, name: 'Azalea Town - Rival Silver'},
  { id: 39, name: 'Ilex Forest - Bug Catcher Wayne'},
  { id: 40, name: 'Route 34 - Youngster Samuel'},
  { id: 41, name: 'Route 34 - Pokefan Brandon'},
  { id: 42, name: 'Route 34 - Picnicker Gina'},
  { id: 43, name: 'Route 34 - Youngster Ian'},
  { id: 44, name: 'Route 34 - Officer Keith'},
  { id: 45, name: 'Route 34 - Camper Todd'},
  { id: 46, name: 'Goldenrod Underground - Super Nerd Eric'},
  { id: 47, name: 'Goldenrod Underground - Pokemaniac Issac'},
  { id: 48, name: 'Goldenrod Underground - Super Nerd Teru'},
  { id: 49, name: 'Goldenrod Underground - Pokemaniac Donald'},
  { id: 50, name: 'Goldenrod City Gym - Beauty Victoria'},
  { id: 51, name: 'Goldenrod City Gym - Beauty Sammantha'},
  { id: 52, name: 'Goldenrod City Gym - Lass Carrie'},
  { id: 53, name: 'Goldenrod City Gym - Lass Bridget'},
  { id: 54, name: 'Goldenrod City Gym - Gym Leader Whitney'},
  { id: 55, name: 'Route 35 - Picnicker Kim'},
  { id: 56, name: 'Route 35 - Camper Elliot'},
  { id: 57, name: 'Route 35 - Picnicker Brooke'},
  { id: 58, name: 'Route 35 - Camper Ivan'},
  { id: 59, name: 'Route 35 - Firebreather Walt'},
  { id: 60, name: 'Route 35 - Juggler Irwin'},
  { id: 61, name: 'Route 35 - Officer Dirk'},
  { id: 62, name: 'Route 35 - Bug Catcher Arnie'},
  { id: 63, name: 'Route 35 - Bird Keeper Bryan'},
  { id: 64, name: 'National Park - Pokefan Beverly'},
  { id: 65, name: 'National Park - Lass Krisse'},
  { id: 66, name: 'National Park - Pokefan William'},
  { id: 67, name: 'National Park - Schoolboy Jack'},
  { id: 68, name: 'Route 36 - Psychic Mark'},
  { id: 69, name: 'Route 36 - Schoolboy Alan'},
  { id: 70, name: 'Route 37 - Twins Ann & Anne'},
  { id: 71, name: 'Route 37 - Psychic Greg'},
  { id: 72, name: 'Burned Tower - 1F - Rival Silver'},
  { id: 73, name: 'Ecruteak City - Kimono Girl Naoko'},
  { id: 74, name: 'Ecruteak City - Kimono Girl Sayo'},
  { id: 75, name: 'Ecruteak City - Kimono Girl Zuki'},
  { id: 76, name: 'Ecruteak City - Kimono Girl Kuni'},
  { id: 77, name: 'Ecruteak City - Kimono Girl Miki'},
  { id: 78, name: 'Ecruteak City Gym - Sage Ping'},
  { id: 79, name: 'Ecruteak City Gym - Medium Grace'},
  { id: 80, name: 'Ecruteak City Gym - Sage Jeffrey'},
  { id: 81, name: 'Ecruteak City Gym - Medium Martha'},
  { id: 82, name: 'Ecruteak City Gym - Gym Leader Morty'},
  { id: 83, name: 'Union Cave - B1F - Hiker Leonard'},
  { id: 84, name: 'Union Cave - B1F - Hiker Phillip'},
  { id: 85, name: 'Ruins of Alph - Psychic Nathan'},
  { id: 86, name: 'Union Cave - B1F - Pokemaniac Andrew'},
  { id: 87, name: 'Union Cave - B1F - Pokemaniac Calvin'},
  { id: 88, name: 'Union Cave - B2F - Cooltrainer Nick'},
  { id: 89, name: 'Union Cave - B2F - Cooltrainer Gwen'},
  { id: 90, name: 'Union Cave - B2F - Cooltrainer Emma'},
  { id: 91, name: 'Route 34 - Cooltrainer Irene'},
  { id: 92, name: 'Route 34 - Cooltrainer Jenn'},
  { id: 93, name: 'Route 34 - Cooltrainer Kate'},
  { id: 94, name: 'Route 46 - Hiker Bailey'},
  { id: 95, name: 'Route 46 - Camper Ted'},
  { id: 96, name: 'Route 46 - Picnicker Erin'},
  { id: 97, name: 'Route 38 - Beauty Valerie'},
  { id: 98, name: 'Route 38 - Bird Keeper Toby'},
  { id: 99, name: 'Route 38 - Sailor Harry'},
  { id: 100, name: 'Route 38 - Lass Dana'},
  { id: 101, name: 'Route 38 - Schoolboy Chad'},
  { id: 102, name: 'Route 38 - Beauty Olivia'},
  { id: 103, name: 'Route 39 - Psychic Norman'},
  { id: 104, name: 'Route 39 - Pokefan Ruth'},
  { id: 105, name: 'Route 39 - Pokefan Derek'},
  { id: 106, name: 'Route 39 - Sailor Eugene'},
  { id: 107, name: 'Route 39 - Pokefan Jaime'},
  { id: 108, name: 'Glitter Lighthouse - 2F - Gentleman Alfred'},
  { id: 109, name: 'Glitter Lighthouse - 2F - Sailor Huey'},
  { id: 110, name: 'Glitter Lighthouse - 3F - Bird Keeper Theo'},
  { id: 111, name: 'Glitter Lighthouse - 3F - Gentleman Preston'},
  { id: 112, name: 'Glitter Lighthouse - 4F - Lass Connie'},
  { id: 113, name: 'Glitter Lighthouse - 4F - Sailor Kent'},
  { id: 114, name: 'Glitter Lighthouse - 5F - Bird Keeper Denis'},
  { id: 115, name: 'Glitter Lighthouse - 3F - Sailor Terrell'},
  { id: 116, name: 'Glitter Lighthouse - 5F - Sailor Ernest'},
  { id: 117, name: 'Route 40 - Swimmer♂ Simon'},
  { id: 118, name: 'Route 40 - Swimmer♀ Elaine'},
  { id: 119, name: 'Route 40 - Swimmer♀ Paula'},
  { id: 120, name: 'Route 40 - Swimmer♂ Randall'},
  { id: 121, name: 'Route 41 - Swimmer♂ Charlie'},
  { id: 122, name: 'Route 41 - Swimmer♂ George'},
  { id: 123, name: 'Route 41 - Swimmer♀ Kara'},
  { id: 124, name: 'Route 41 - Swimmer♂ Matthew'},
  { id: 125, name: 'Route 41 - Swimmer♀ Denise'},
  { id: 126, name: 'Route 41 - Swimmer♂ Kirk'},
  { id: 127, name: 'Route 41 - Swimmer♂ Berke'},
  { id: 128, name: 'Route 41 - Swimmer♀ Susie'},
  { id: 129, name: 'Route 41 - Swimmer♀ Kaylee'},
  { id: 130, name: 'Route 41 - Swimmer♀ Wendy'},
  { id: 131, name: 'Cianwood City - MysticalMan Eusine'},
  { id: 132, name: 'Cianwood City Gym - Blackbelt Yoshi'},
  { id: 133, name: 'Cianwood City Gym - Blackbelt Lao'},
  { id: 134, name: 'Cianwood City Gym - Blackbelt Nob'},
  { id: 135, name: 'Cianwood City Gym - Blackbelt Lung'},
  { id: 136, name: 'Cianwood City Gym - Gym Leader Chuck'},
  { id: 137, name: 'Olivine City Gym - Gym Leader Jasmine'},
  { id: 138, name: 'Route 42 - Fisher Tully'},
  { id: 139, name: 'Route 42 - Pokemaniac Shane'},
  { id: 140, name: 'Route 42 - Hiker Benjamin'},
  { id: 141, name: 'Mt. Mortar - Pokemaniac Miller'},
  { id: 142, name: 'Mt. Mortar - Super Nerd Markus'},
  { id: 143, name: 'Route 43 - Camper Spencer'},
  { id: 144, name: 'Route 43 - Picnicker Tiffany'},
  { id: 145, name: 'Route 43 - Pokemaniac Brent'},
  { id: 146, name: 'Route 43 - Pokemaniac Ron'},
  { id: 147, name: 'Route 43 - Pokemaniac Ben'},
  { id: 148, name: 'Route 43 - Fisher Marvin'},
  { id: 149, name: 'Team Rocket Hideout - B1F - Rocket Grunt #1'},
  { id: 150, name: 'Team Rocket Hideout - B1F - Rocket Grunt #2'},
  { id: 151, name: 'Team Rocket Hideout - B1F - Scientist Jed'},
  { id: 152, name: 'Team Rocket Hideout - B1F - Rocket Grunt #3'},
  { id: 153, name: 'Team Rocket Hideout - B2F - Rocket Grunt #4'},
  { id: 154, name: 'Team Rocket Hideout - B2F - Rocket Grunt #5'},
  { id: 155, name: 'Team Rocket Hideout - B3F - Scientist Ross'},
  { id: 156, name: 'Team Rocket Hideout - B3F - Rocket Grunt #6'},
  { id: 157, name: 'Team Rocket Hideout - B3F - Scientist Mitch'},
  { id: 158, name: 'Team Rocket Hideout - B3F - Rocket Grunt #7'},
  { id: 159, name: 'Team Rocket Hideout - B2F - Rocket Grunt #8'},
  { id: 160, name: 'Team Rocket Hideout - B3F - Rocket Executive #1'},
  { id: 161, name: 'Team Rocket Hideout - B2F - Rocket Executive #2'},
  { id: 162, name: 'Mahogany Town Gym - Skier Roxanne'},
  { id: 163, name: 'Mahogany Town Gym - Boarder Brad'},
  { id: 164, name: 'Mahogany Town Gym - Skier Clarissa'},
  { id: 165, name: 'Mahogany Town Gym - Boarder Douglas'},
  { id: 166, name: 'Mahogany Town Gym - Boarder Ronald'},
  { id: 167, name: 'Mahogany Town Gym - Gym Leader Pryce'},
  { id: 168, name: 'Goldenrod City - Radio Tower 1F - Rocket Grunt'},
  { id: 169, name: 'Goldenrod City - Radio Tower 2F - Rocket Grunt Near Buena'},
  { id: 170, name: 'Goldenrod City - Radio Tower 2F - Rocket Grunt Top Path'},
  { id: 171, name: 'Goldenrod City - Radio Tower 2F - Rocket Grunt Bottom Path'},
  { id: 172, name: 'Goldenrod City - Radio Tower 2F - Rocket Grunt Near Stairs'},
  { id: 173, name: 'Goldenrod City - Radio Tower 3F - Rocket Grunt Facing Down'},
  { id: 174, name: 'Goldenrod City - Radio Tower 3F - Rocket Grunt Facing Right'},
  { id: 175, name: 'Goldenrod City - Radio Tower - Scientist Marc'},
  { id: 176, name: 'Goldenrod City - Radio Tower 4F - Left Side - Rocket Grunt'},
  { id: 177, name: 'Goldenrod City - Radio Tower - Scientist Rich'},
  { id: 178, name: 'Goldenrod City - Radio Tower 5F - Left Side - Rocket Executive'},
  { id: 179, name: 'Goldenrod City - Underground Warehouse - Rival Silver'},
  { id: 180, name: 'Goldenrod City - Underground Warehouse - Rocket Grunt #9'},
  { id: 181, name: 'Goldenrod City - Underground Warehouse - Rocket Grunt #10'},
  { id: 182, name: 'Goldenrod City - Underground Warehouse - Rocket Grunt #11'},
  { id: 183, name: 'Goldenrod City - Underground Warehouse - Burgular Eddie'},
  { id: 184, name: 'Goldenrod City - Underground Warehouse - Burgular Duncan'},
  { id: 185, name: 'Goldenrod City - Underground Warehouse - Rocket Grunt #12'},
  { id: 186, name: 'Goldenrod City - Underground Warehouse - Rocket Grunt #13'},
  { id: 187, name: 'Goldenrod City - Underground Warehouse - Rocket Grunt #14'},
  { id: 188, name: 'Goldenrod City - Underground Warehouse - Rocket Grunt #15'},
  { id: 189, name: 'Goldenrod City - Radio Tower - Rocket Grunt #16'},
  { id: 190, name: 'Goldenrod City - Radio Tower - Rocket Grunt #17'},
  { id: 191, name: 'Goldenrod City - Radio Tower - Rocket Executive #2'},
  { id: 192, name: 'Goldenrod City - Radio Tower - Rocket Executive #3'},
  { id: 193, name: 'Goldenrod City - Radio Tower - Rocket Executive #4'},
  { id: 194, name: 'Route 44 - Psychic Phil'},
  { id: 195, name: 'Route 44 - Fisher Wilton'},
  { id: 196, name: 'Route 44 - Pokemaniac Zach'},
  { id: 197, name: 'Route 44 - Cooltrainer Cybil'},
  { id: 198, name: 'Route 44 - Fisher Edgar'},
  { id: 199, name: 'Route 44 - Bird Keeper Vance'},
  { id: 200, name: 'Blackthorn City Gym - Cooltrainer Paul'},
  { id: 201, name: 'Blackthorn City Gym - Cooltrainer Fran'},
  { id: 202, name: 'Blackthorn City Gym - Cooltrainer Cody'},
  { id: 203, name: 'Blackthorn City Gym - Cooltrainer Mike'},
  { id: 204, name: 'Blackthorn City Gym - Gym Leader Clair'},
  { id: 205, name: 'Dragon\'s Den - Cooltrainer Cara'},
  { id: 206, name: 'Dragon\'s Den - Cooltrainer Darin'},
  { id: 207, name: 'Dragon\'s Den - Twins Lea & Pia'},
  { id: 208, name: 'Mt. Mortar - Blackbelt Kiyo'},
  { id: 209, name: 'Route 45 - Hiker Erik'},
  { id: 210, name: 'Route 45 - Cooltrainer Ryan'},
  { id: 211, name: 'Route 45 - Hiker Parry'},
  { id: 212, name: 'Route 45 - Cooltrainer Kelly'},
  { id: 213, name: 'Route 45 - Blackbelt Kenji'},
  { id: 214, name: 'Route 45 - Hiker Timothy'},
  { id: 215, name: 'Route 45 - Hiker Michael'},
  { id: 216, name: 'Route 27 - Cooltrainer Megan'},
  { id: 217, name: 'Route 27 - Cooltrainer Blake'},
  { id: 218, name: 'Route 27 - Cooltrainer Brian'},
  { id: 219, name: 'Route 27 - Psychic Gilbert'},
  { id: 220, name: 'Route 27 - Bird Keeper Jose'},
  { id: 221, name: 'Route 27 - Cooltrainer Reena'},
  { id: 222, name: 'Route 26 - Fisher Scott'},
  { id: 223, name: 'Route 26 - Psychic Richard'},
  { id: 224, name: 'Route 26 - Cooltrainer Joyce'},
  { id: 225, name: 'Route 26 - Cooltrainer Gaven'},
  { id: 226, name: 'Route 26 - Cooltrainer Jake'},
  { id: 227, name: 'Route 26 - Cooltrainer Beth'},
  { id: 228, name: 'Victory Road - Rival Silver'},
  { id: 229, name: 'Indigo Plateau Pokemon League - Kanto Elite Four Will'},
  { id: 230, name: 'Indigo Plateau Pokemon League - Kanto Elite Four Koga'},
  { id: 231, name: 'Indigo Plateau Pokemon League - Kanto Elite Four Bruno'},
  { id: 232, name: 'Indigo Plateau Pokemon League - Kanto Elite Four Karen'},
  { id: 233, name: 'Indigo Plateau Pokemon League - Champion Lance'},
  { id: 234, name: 'Mt. Mortar - Super Nerd Hugh'},
  { id: 235, name: 'S.S. Aqua - Hiker Noland'},
  { id: 236, name: 'S.S. Aqua - Firebreather Lyle'},
  { id: 237, name: 'S.S. Aqua - Pokefan Colin'},
  { id: 238, name: 'S.S. Aqua - Twins Meg & Peg'},
  { id: 239, name: 'S.S. Aqua - Sailor Stanly'},
  { id: 240, name: 'S.S. Aqua - Juggler Fritz'},
  { id: 241, name: 'S.S. Aqua - Sailor Jeff'},
  { id: 242, name: 'S.S. Aqua - Picnicker Debra'},
  { id: 243, name: 'Vermilion City Gym - Guitarist Vincent'},
  { id: 244, name: 'Vermilion City Gym - Juggler Horton'},
  { id: 245, name: 'Vermilion City Gym - Gentleman Gregory'},
  { id: 246, name: 'Vermilion City Gym - Gym Leader Lt. Surge'},
  { id: 247, name: 'Saffron City Gym - Medium Rebecca'},
  { id: 248, name: 'Saffron City Gym - Psychic Franklin'},
  { id: 249, name: 'Saffron City Gym - Psychic Jared'},
  { id: 250, name: 'Saffron City Gym - Medium Doris'},
  { id: 251, name: 'Saffron City Gym - Gym Leader Sabrina'},
  { id: 252, name: 'Celadon City Gym - Twins Jo & Zoe'},
  { id: 253, name: 'Celadon City Gym - Lass Michelle'},
  { id: 254, name: 'Celadon City Gym - Picnicker Tanya'},
  { id: 255, name: 'Celadon City Gym - Beauty Julia'},
  { id: 256, name: 'Celadon City Gym - Gym Leader Erika'},
  { id: 257, name: 'Route 17 - Biker Riley'},
  { id: 258, name: 'Route 17 - Biker Glenn'},
  { id: 259, name: 'Route 17 - Biker Joel'},
  { id: 260, name: 'Route 17 - Biker Charles'},
  { id: 261, name: 'Route 18 - Bird Keeper Bob'},
  { id: 262, name: 'Route 18 - Bird Keeper Boris'},
  { id: 263, name: 'Fuschia City Gym - Lass Linda'},
  { id: 264, name: 'Fuschia City Gym - Picnicker Cindy'},
  { id: 265, name: 'Fuschia City Gym - Camper Barry'},
  { id: 266, name: 'Fuschia City Gym - Lass Alice'},
  { id: 267, name: 'Fuschia City Gym - Gym Leader Janine'},
  { id: 268, name: 'Route 9 - Picnicker Edna'},
  { id: 269, name: 'Route 9 - Camper Sid'},
  { id: 270, name: 'Route 9 - Camper Dean'},
  { id: 271, name: 'Route 9 - Hiker Sidney'},
  { id: 272, name: 'Route 9 - Hiker Tim'},
  { id: 273, name: 'Route 9 - Picnicker Heidi'},
  { id: 274, name: 'Route 24 - Rocket Grunt'},
  { id: 275, name: 'Route 24 - Schoolboy Dudley'},
  { id: 276, name: 'Route 24 - Lass Ellen'},
  { id: 277, name: 'Route 25 - Schoolboy Joe'},
  { id: 278, name: 'Route 25 - Lass Laura'},
  { id: 279, name: 'Route 25 - Camper Lloyd'},
  { id: 280, name: 'Route 25 - Lass Shannon'},
  { id: 281, name: 'Route 25 - Super Nerd Pat'},
  { id: 282, name: 'Route 25 - Cooltrainer Kevin'},
  { id: 283, name: 'Cerulean City Gym - Swimmer♀ Brianna'},
  { id: 284, name: 'Cerulean City Gym - Swimmer♀ Parker'},
  { id: 285, name: 'Cerulean City Gym - Swimmer♀ Diana'},
  { id: 286, name: 'Cerulean City Gym - Gym Leader Misty'},
  { id: 287, name: 'Route 8 - Biker Dwayne'},
  { id: 288, name: 'Route 8 - Biker Harris'},
  { id: 289, name: 'Route 8 - Biker Zeke'},
  { id: 290, name: 'Route 8 - Super Nerd Sam'},
  { id: 291, name: 'Route 8 - Super Nerd Tom'},
  { id: 292, name: 'Route 2 - Bug Catcher Ed'},
  { id: 293, name: 'Pewter City Gym - Camper Jerry'},
  { id: 294, name: 'Pewter City Gym - Gym Leader Brock'},
  { id: 295, name: 'Route 2 - Bug Catcher Doug'},
  { id: 296, name: 'Route 2 - Bug Catcher Rob'},
  { id: 297, name: 'Route 21 - Swimmer♀ Nikki'},
  { id: 298, name: 'Route 21 - Fisher Arnold'},
  { id: 299, name: 'Route 21 - Swimmer♂ Seth'},
  { id: 300, name: 'Route 20 - Swimmer♂ Cameron'},
  { id: 301, name: 'Route 20 - Swimmer♀ Lori'},
  { id: 302, name: 'Route 20 - Swimmer♀ Nicole'},
  { id: 303, name: 'Seafoam Islands Gym - Gym Leader Blaine'},
  { id: 304, name: 'Viridian City Gym - Gym Leader Blue'},
  { id: 305, name: 'Route 3 - Youngster Warren'},
  { id: 306, name: 'Route 3 - Youngster Jimmy'},
  { id: 307, name: 'Route 3 - Firebreather Otis'},
  { id: 308, name: 'Route 3 - Firebreather Burt'},
  { id: 309, name: 'Mt. Moon - Rival Silver'},
  { id: 310, name: 'Route 4 - Picnicker Hope'},
  { id: 311, name: 'Route 4 - Bird Keeper Hawk'},
  { id: 312, name: 'Route 4 - Picnicker Sharon'},
  { id: 313, name: 'Route 19 - Swimmer♂ Jerome'},
  { id: 314, name: 'Route 19 - Swimmer♀ Dawn'},
  { id: 315, name: 'Route 19 - Swimmer♂ Tucker'},
  { id: 316, name: 'Route 19 - Swimmer♂ Harold'},
  { id: 317, name: 'Route 10 - Hiker Jim'},
  { id: 318, name: 'Route 10 - Pokefan Robert'},
  { id: 319, name: 'Route 11 - Psychic Fidel'},
  { id: 320, name: 'Route 11 - Youngster Jason'},
  { id: 321, name: 'Route 11 - Youngster Owen'},
  { id: 322, name: 'Route 11 - Psychic Herman'},
  { id: 323, name: 'Route 12 - Fisher Martin'},
  { id: 324, name: 'Route 12 - Fisher Kyle'},
  { id: 325, name: 'Route 12 - Fisher Stephen'},
  { id: 326, name: 'Route 12 - Fisher Barney'},
  { id: 327, name: 'Route 13 - Bird Keeper Bret'},
  { id: 328, name: 'Route 13 - Bird Keeper Perry'},
  { id: 329, name: 'Route 13 - Pokefan Joshua'},
  { id: 330, name: 'Route 13 - Pokefan Alex'},
  { id: 331, name: 'Route 13 - Hiker Kenny'},
  { id: 332, name: 'Route 14 - Pokefan Carter'},
  { id: 333, name: 'Route 14 - Bird Keeper Roy'},
  { id: 334, name: 'Route 15 - Schoolboy Johnny'},
  { id: 335, name: 'Route 15 - Teacher Colette'},
  { id: 336, name: 'Route 15 - Schoolboy Billy'},
  { id: 337, name: 'Route 15 - Teacher Hillary'},
  { id: 338, name: 'Route 15 - Schoolboy Tommy'},
  { id: 339, name: 'Route 15 - Schoolboy Kip'},
  { id: 340, name: 'Mount Silver - Pokemon Trainer Red'},
  { id: 341, name: 'Route 6 - Pokefan Rex'},
  { id: 342, name: 'Route 6 - Pokefan Allan'},
];

export default RIVALS;
