// TODO? Should we get screenshots of each trainer and use pictures instead of text
const RIVALS = [
  { id: 1, location: 'Cherrygrove City', name: '???'},
  { id: 2, location: 'Route 30', name: 'Youngster Joey'},
  { id: 3, location: 'Route 30', name: 'Youngster Mikey'},
  { id: 4, location: 'Route 30', name: 'Bug Catcher Don'},
  { id: 5, location: 'Route 31', name: 'Bug Catcher Wade'},
  { id: 6, location: 'Sprout Tower - 2F', name: 'Sage Nico'},
  { id: 7, location: 'Sprout Tower - 1F', name: 'Sage Chow'},
  { id: 8, location: 'Sprout Tower - 2F', name: 'Sage Edmond'},
  { id: 9, location: 'Sprout Tower - 3F', name: 'Sage Neal'},
  { id: 10, location: 'Sprout Tower - 3F', name: 'Sage Troy'},
  { id: 11, location: 'Sprout Tower - 3F', name: 'Sage Li'},
  { id: 12, location: 'Violet City Gym', name: 'Bird Keeper Abe'},
  { id: 13, location: 'Violet City Gym', name: 'Bird Keeper Rod'},
  { id: 14, location: 'Violet City Gym', name: 'Gym Leader Falkner'},
  { id: 15, location: 'Route 32', name: 'Youngster Albert'},
  { id: 16, location: 'Route 32', name: 'Picnicker Liz'},
  { id: 17, location: 'Route 32', name: 'Camper Roland'},
  { id: 18, location: 'Route 32', name: 'Youngster Gordon'},
  { id: 19, location: 'Route 32', name: 'Fisher Ralph'},
  { id: 20, location: 'Route 32', name: 'Fisher Justin'},
  { id: 21, location: 'Route 32', name: 'Fisher Henry'},
  { id: 22, location: 'Route 32', name: 'Bird Keeper Peter'},
  { id: 23, location: 'Union Cave - 1F', name: 'Hiker Daniel'},
  { id: 24, location: 'Union Cave - 1F', name: 'Hiker Russel'},
  { id: 25, location: 'Union Cave - 1F', name: 'Firebreather Bill'},
  { id: 26, location: 'Union Cave - 1F', name: 'Pokemaniac Larry'},
  { id: 27, location: 'Union Cave - 1F', name: 'Firebreather Ray'},
  { id: 28, location: 'Route 33', name: 'Hiker Anthony'},
  { id: 29, location: 'Slowpoke Well - B1F', name: 'Rocket Grunt before Plateau'},
  { id: 30, location: 'Slowpoke Well - B1F', name: 'Rocket Grunt on Plateau'},
  { id: 31, location: 'Slowpoke Well - B1F', name: 'Rocket Grunt after Plateau'},
  { id: 32, location: 'Slowpoke Well - B1F', name: 'Last Rocket Grunt'},
  { id: 33, location: 'Azalea Town Gym', name: 'Twins Amy & May'},
  { id: 34, location: 'Azalea Town Gym', name: 'Bug Catcher Al', missable: true},
  { id: 35, location: 'Azalea Town Gym', name: 'Bug Catcher Benny', missable: true},
  { id: 36, location: 'Azalea Town Gym', name: 'Bug Catcher Josh', missable: true},
  { id: 37, location: 'Azalea Town Gym', name: 'Gym Leader Bugsy'},
  { id: 38, location: 'Azalea Town', name: 'Rival Silver'},
  { id: 39, location: 'Ilex Forest', name: 'Bug Catcher Wayne'},
  { id: 40, location: 'Route 34', name: 'Youngster Samuel'},
  { id: 41, location: 'Route 34', name: 'Pokefan Brandon'},
  { id: 42, location: 'Route 34', name: 'Picnicker Gina'},
  { id: 43, location: 'Route 34', name: 'Youngster Ian'},
  { id: 44, location: 'Route 34', name: 'Officer Keith'},
  { id: 45, location: 'Route 34', name: 'Camper Todd'},
  { id: 46, location: 'Goldenrod Underground', name: 'Super Nerd Eric'},
  { id: 47, location: 'Goldenrod Underground', name: 'Pokemaniac Issac'},
  { id: 48, location: 'Goldenrod Underground', name: 'Super Nerd Teru'},
  { id: 49, location: 'Goldenrod Underground', name: 'Pokemaniac Donald'},
  { id: 50, location: 'Goldenrod City Gym', name: 'Beauty Victoria', missable: true},
  { id: 51, location: 'Goldenrod City Gym', name: 'Beauty Sammantha', missable: true},
  { id: 52, location: 'Goldenrod City Gym', name: 'Lass Carrie'},
  { id: 53, location: 'Goldenrod City Gym', name: 'Lass Bridget', missable: true},
  { id: 54, location: 'Goldenrod City Gym', name: 'Gym Leader Whitney'},
  { id: 55, location: 'Route 35', name: 'Picnicker Kim'},
  { id: 56, location: 'Route 35', name: 'Camper Elliot'},
  { id: 57, location: 'Route 35', name: 'Picnicker Brooke'},
  { id: 58, location: 'Route 35', name: 'Camper Ivan'},
  { id: 59, location: 'Route 35', name: 'Firebreather Walt'},
  { id: 60, location: 'Route 35', name: 'Juggler Irwin'},
  { id: 61, location: 'Route 35', name: 'Officer Dirk'},
  { id: 62, location: 'Route 35', name: 'Bug Catcher Arnie'},
  { id: 63, location: 'Route 35', name: 'Bird Keeper Bryan'},
  { id: 64, location: 'National Park', name: 'Pokefan Beverly'},
  { id: 65, location: 'National Park', name: 'Lass Krisse'},
  { id: 66, location: 'National Park', name: 'Pokefan William'},
  { id: 67, location: 'National Park', name: 'Schoolboy Jack'},
  { id: 68, location: 'Route 36', name: 'Psychic Mark'},
  { id: 69, location: 'Route 36', name: 'Schoolboy Alan'},
  { id: 70, location: 'Route 37', name: 'Twins Ann & Anne'},
  { id: 71, location: 'Route 37', name: 'Psychic Greg'},
  { id: 72, location: 'Burned Tower - 1F', name: 'Rival Silver'},
  { id: 73, location: 'Ecruteak City', name: 'Kimono Girl Naoko'},
  { id: 74, location: 'Ecruteak City', name: 'Kimono Girl Sayo'},
  { id: 75, location: 'Ecruteak City', name: 'Kimono Girl Zuki'},
  { id: 76, location: 'Ecruteak City', name: 'Kimono Girl Kuni'},
  { id: 77, location: 'Ecruteak City', name: 'Kimono Girl Miki'},
  { id: 78, location: 'Ecruteak City Gym', name: 'Sage Ping'},
  { id: 79, location: 'Ecruteak City Gym', name: 'Medium Grace', missable: true},
  { id: 80, location: 'Ecruteak City Gym', name: 'Sage Jeffrey'},
  { id: 81, location: 'Ecruteak City Gym', name: 'Medium Martha'},
  { id: 82, location: 'Ecruteak City Gym', name: 'Gym Leader Morty'},
  { id: 83, location: 'Union Cave - B1F', name: 'Hiker Leonard'},
  { id: 84, location: 'Union Cave - B1F', name: 'Hiker Phillip'},
  { id: 85, location: 'Ruins of Alph', name: 'Psychic Nathan'},
  { id: 86, location: 'Union Cave - B1F', name: 'Pokemaniac Andrew'},
  { id: 87, location: 'Union Cave - B1F', name: 'Pokemaniac Calvin'},
  { id: 88, location: 'Union Cave - B2F', name: 'Cooltrainer Nick'},
  { id: 89, location: 'Union Cave - B2F', name: 'Cooltrainer Gwen'},
  { id: 90, location: 'Union Cave - B2F', name: 'Cooltrainer Emma'},
  { id: 91, location: 'Route 34', name: 'Cooltrainer Irene'},
  { id: 92, location: 'Route 34', name: 'Cooltrainer Jenn'},
  { id: 93, location: 'Route 34', name: 'Cooltrainer Kate'},
  { id: 94, location: 'Route 46', name: 'Hiker Bailey'},
  { id: 95, location: 'Route 46', name: 'Camper Ted'},
  { id: 96, location: 'Route 46', name: 'Picnicker Erin'},
  { id: 97, location: 'Route 38', name: 'Beauty Valerie'},
  { id: 98, location: 'Route 38', name: 'Bird Keeper Toby'},
  { id: 99, location: 'Route 38', name: 'Sailor Harry'},
  { id: 100, location: 'Route 38', name: 'Lass Dana'},
  { id: 101, location: 'Route 38', name: 'Schoolboy Chad'},
  { id: 102, location: 'Route 38', name: 'Beauty Olivia'},
  { id: 103, location: 'Route 39', name: 'Psychic Norman'},
  { id: 104, location: 'Route 39', name: 'Pokefan Ruth'},
  { id: 105, location: 'Route 39', name: 'Pokefan Derek'},
  { id: 106, location: 'Route 39', name: 'Sailor Eugene'},
  { id: 107, location: 'Route 39', name: 'Pokefan Jaime'},
  { id: 108, location: 'Glitter Lighthouse - 2F', name: 'Gentleman Alfred'},
  { id: 109, location: 'Glitter Lighthouse - 2F', name: 'Sailor Huey'},
  { id: 110, location: 'Glitter Lighthouse - 3F', name: 'Bird Keeper Theo'},
  { id: 111, location: 'Glitter Lighthouse - 3F', name: 'Gentleman Preston'},
  { id: 112, location: 'Glitter Lighthouse - 4F', name: 'Lass Connie'},
  { id: 113, location: 'Glitter Lighthouse - 4F', name: 'Sailor Kent'},
  { id: 114, location: 'Glitter Lighthouse - 5F', name: 'Bird Keeper Denis'},
  { id: 115, location: 'Glitter Lighthouse - 3F', name: 'Sailor Terrell'},
  { id: 116, location: 'Glitter Lighthouse - 5F', name: 'Sailor Ernest'},
  { id: 117, location: 'Route 40', name: 'Swimmer♂ Simon'},
  { id: 118, location: 'Route 40', name: 'Swimmer♀ Elaine'},
  { id: 119, location: 'Route 40', name: 'Swimmer♀ Paula'},
  { id: 120, location: 'Route 40', name: 'Swimmer♂ Randall'},
  { id: 121, location: 'Route 41', name: 'Swimmer♂ Charlie'},
  { id: 122, location: 'Route 41', name: 'Swimmer♂ George'},
  { id: 123, location: 'Route 41', name: 'Swimmer♀ Kara'},
  { id: 124, location: 'Route 41', name: 'Swimmer♂ Matthew'},
  { id: 125, location: 'Route 41', name: 'Swimmer♀ Denise'},
  { id: 126, location: 'Route 41', name: 'Swimmer♂ Kirk'},
  { id: 127, location: 'Route 41', name: 'Swimmer♂ Berke'},
  { id: 128, location: 'Route 41', name: 'Swimmer♀ Susie'},
  { id: 129, location: 'Route 41', name: 'Swimmer♀ Kaylee'},
  { id: 130, location: 'Route 41', name: 'Swimmer♀ Wendy'},
  { id: 131, location: 'Cianwood City', name: 'MysticalMan Eusine'},
  { id: 132, location: 'Cianwood City Gym', name: 'Blackbelt Yoshi'},
  { id: 133, location: 'Cianwood City Gym', name: 'Blackbelt Lao'},
  { id: 134, location: 'Cianwood City Gym', name: 'Blackbelt Nob'},
  { id: 135, location: 'Cianwood City Gym', name: 'Blackbelt Lung'},
  { id: 136, location: 'Cianwood City Gym', name: 'Gym Leader Chuck'},
  { id: 137, location: 'Olivine City Gym', name: 'Gym Leader Jasmine'},
  { id: 138, location: 'Route 42', name: 'Fisher Tully'},
  { id: 139, location: 'Route 42', name: 'Pokemaniac Shane'},
  { id: 140, location: 'Route 42', name: 'Hiker Benjamin'},
  { id: 141, location: 'Mt. Mortar', name: 'Pokemaniac Miller'},
  { id: 142, location: 'Mt. Mortar', name: 'Super Nerd Markus'},
  { id: 143, location: 'Route 43', name: 'Camper Spencer'},
  { id: 144, location: 'Route 43', name: 'Picnicker Tiffany'},
  { id: 145, location: 'Route 43', name: 'Pokemaniac Brent'},
  { id: 146, location: 'Route 43', name: 'Pokemaniac Ron'},
  { id: 147, location: 'Route 43', name: 'Pokemaniac Ben'},
  { id: 148, location: 'Route 43', name: 'Fisher Marvin'},
  { id: 149, location: 'Team Rocket Hideout - B1F', name: 'Statue Alert Rocket Grunt #1'},
  { id: 150, location: 'Team Rocket Hideout - B1F', name: 'Statue Alert Rocket Grunt #2'},
  { id: 151, location: 'Team Rocket Hideout - B1F', name: 'Scientist Jed'},
  { id: 152, location: 'Team Rocket Hideout - B1F', name: 'Rocket Grunt near traps'},
  { id: 153, location: 'Team Rocket Hideout - B2F', name: 'Rocket Grunt near generator doors'},
  { id: 154, location: 'Team Rocket Hideout - B2F', name: 'Rocket Grunt near stairs'},
  { id: 155, location: 'Team Rocket Hideout - B3F', name: 'Scientist Ross'},
  { id: 156, location: 'Team Rocket Hideout - B3F', name: 'Password Rocket Grunt at computer'},
  { id: 157, location: 'Team Rocket Hideout - B3F', name: 'Scientist Mitch'},
  { id: 158, location: 'Team Rocket Hideout - B3F', name: 'Password Spinner Rocket Grunt'},
  { id: 159, location: 'Team Rocket Hideout - B2F', name: 'Spinner Rocket Grunt'},
  { id: 160, location: 'Team Rocket Hideout - B3F', name: 'Rocket Executive near Murkrow'},
  { id: 161, location: 'Team Rocket Hideout - B2F', name: 'Rocket Executive near generator doors'},
  { id: 162, location: 'Mahogany Town Gym', name: 'Skier Roxanne', missable: true},
  { id: 163, location: 'Mahogany Town Gym', name: 'Boarder Brad', missable: true},
  { id: 164, location: 'Mahogany Town Gym', name: 'Skier Clarissa', missable: true},
  { id: 165, location: 'Mahogany Town Gym', name: 'Boarder Douglas', missable: true},
  { id: 166, location: 'Mahogany Town Gym', name: 'Boarder Ronald', missable: true},
  { id: 167, location: 'Mahogany Town Gym', name: 'Gym Leader Pryce'},
  { id: 168, location: 'Goldenrod City - Radio Tower 1F', name: 'Rocket Grunt'},
  { id: 169, location: 'Goldenrod City - Radio Tower 2F', name: 'Rocket Grunt Near Buena'},
  { id: 170, location: 'Goldenrod City - Radio Tower 2F', name: 'Rocket Grunt Top Path', missable: true},
  { id: 171, location: 'Goldenrod City - Radio Tower 2F', name: 'Rocket Grunt Bottom Path', missable: true},
  { id: 172, location: 'Goldenrod City - Radio Tower 2F', name: 'Rocket Grunt Near Stairs'},
  { id: 173, location: 'Goldenrod City - Radio Tower 3F', name: 'Rocket Grunt Facing Down', missable: true},
  { id: 174, location: 'Goldenrod City - Radio Tower 3F', name: 'Rocket Grunt Facing Right', missable: true},
  { id: 175, location: 'Goldenrod City - Radio Tower 3F', name: 'Scientist Marc', missable: true},
  { id: 176, location: 'Goldenrod City - Radio Tower 4F - Left Side', name: 'Spinner Rocket Grunt', missable: true},
  { id: 177, location: 'Goldenrod City - Radio Tower 4F', name: 'Scientist Rich', missable: true},
  { id: 178, location: 'Goldenrod City - Radio Tower 5F - Left Side', name: 'Rocket False Director'},
  { id: 179, location: 'Goldenrod City - Underground Warehouse', name: 'Rival Silver'},
  { id: 180, location: 'Goldenrod City - Underground Warehouse', name: 'Rocket Grunt near Switch 1', missable: true},
  { id: 181, location: 'Goldenrod City - Underground Warehouse', name: 'Rocket Grunt near Switch 2', missable: true},
  { id: 182, location: 'Goldenrod City - Underground Warehouse', name: 'Rocket Grunt near Switch 3', missable: true},
  { id: 183, location: 'Goldenrod City - Underground Warehouse', name: 'Burglar Eddie', missable: true},
  { id: 184, location: 'Goldenrod City - Underground Warehouse', name: 'Burglar Duncan', missable: true},
  { id: 185, location: 'Goldenrod City - Underground Warehouse', name: 'Rocket Grunt Near Emergency Switch', missable: true},
  { id: 186, location: 'Goldenrod City - Underground Warehouse', name: 'Rocket Grunt By Crates', missable: true},
  { id: 187, location: 'Goldenrod City - Underground Warehouse', name: 'Rocket Grunt Near Stairs', missable: true},
  { id: 188, location: 'Goldenrod City - Underground Warehouse', name: 'Rocket Grunt Near Director', missable: true},
  { id: 189, location: 'Goldenrod City - Radio Tower 3F', name: 'Rocket Grunt Behind Shutters'},
  { id: 190, location: 'Goldenrod City - Radio Tower 4F', name: 'Rocket Grunt Near DJ Mary', missable: true},
  { id: 191, location: 'Goldenrod City - Radio Tower 4F', name: 'Rocket Executive Near Stairs'},
  { id: 192, location: 'Goldenrod City - Radio Tower 5F', name: 'Rocket Executive Before Radio Booth'},
  { id: 193, location: 'Goldenrod City - Radio Tower 5F', name: 'Rocket Executive In Radio Booth'},
  { id: 194, location: 'Route 44', name: 'Psychic Phil'},
  { id: 195, location: 'Route 44', name: 'Fisher Wilton'},
  { id: 196, location: 'Route 44', name: 'Pokemaniac Zach'},
  { id: 197, location: 'Route 44', name: 'Cooltrainer Cybil'},
  { id: 198, location: 'Route 44', name: 'Fisher Edgar'},
  { id: 199, location: 'Route 44', name: 'Bird Keeper Vance'},
  { id: 200, location: 'Blackthorn City Gym', name: 'Cooltrainer Paul'},
  { id: 201, location: 'Blackthorn City Gym', name: 'Cooltrainer Fran'},
  { id: 202, location: 'Blackthorn City Gym', name: 'Cooltrainer Cody'},
  { id: 203, location: 'Blackthorn City Gym', name: 'Cooltrainer Mike', missable: true},
  { id: 204, location: 'Blackthorn City Gym', name: 'Cooltrainer Lola'},
  { id: 205, location: 'Blackthorn City Gym', name: 'Gym Leader Clair'},
  { id: 206, location: 'Dragon\'s Den', name: 'Cooltrainer Cara'},
  { id: 207, location: 'Dragon\'s Den', name: 'Cooltrainer Darin'},
  { id: 208, location: 'Dragon\'s Den', name: 'Twins Lea & Pia'},
  { id: 209, location: 'Mt. Mortar', name: 'Blackbelt Kiyo'},
  { id: 210, location: 'Route 45', name: 'Hiker Erik'},
  { id: 211, location: 'Route 45', name: 'Cooltrainer Ryan'},
  { id: 212, location: 'Route 45', name: 'Hiker Parry'},
  { id: 213, location: 'Route 45', name: 'Cooltrainer Kelly'},
  { id: 214, location: 'Route 45', name: 'Blackbelt Kenji'},
  { id: 215, location: 'Route 45', name: 'Hiker Timothy'},
  { id: 216, location: 'Route 45', name: 'Hiker Michael'},
  { id: 217, location: 'Route 27', name: 'Cooltrainer Megan'},
  { id: 218, location: 'Route 27', name: 'Cooltrainer Blake'},
  { id: 219, location: 'Route 27', name: 'Cooltrainer Brian'},
  { id: 220, location: 'Route 27', name: 'Psychic Gilbert'},
  { id: 221, location: 'Route 27', name: 'Bird Keeper Jose'},
  { id: 222, location: 'Route 27', name: 'Cooltrainer Reena'},
  { id: 223, location: 'Route 26', name: 'Fisher Scott'},
  { id: 224, location: 'Route 26', name: 'Psychic Richard'},
  { id: 225, location: 'Route 26', name: 'Cooltrainer Joyce'},
  { id: 226, location: 'Route 26', name: 'Cooltrainer Gaven'},
  { id: 227, location: 'Route 26', name: 'Cooltrainer Jake'},
  { id: 228, location: 'Route 26', name: 'Cooltrainer Beth'},
  { id: 229, location: 'Victory Road', name: 'Rival Silver'},
  { id: 230, location: 'Indigo Plateau Pokemon League', name: 'Kanto Elite Four Will'},
  { id: 231, location: 'Indigo Plateau Pokemon League', name: 'Kanto Elite Four Koga'},
  { id: 232, location: 'Indigo Plateau Pokemon League', name: 'Kanto Elite Four Bruno'},
  { id: 233, location: 'Indigo Plateau Pokemon League', name: 'Kanto Elite Four Karen'},
  { id: 234, location: 'Indigo Plateau Pokemon League', name: 'Champion Lance'},
  { id: 235, location: 'Mt. Mortar', name: 'Super Nerd Hugh'},
  { id: 236, location: 'S.S. Aqua', name: 'Hiker Noland', missable: true},
  { id: 237, location: 'S.S. Aqua', name: 'Firebreather Lyle', missable: true},
  { id: 238, location: 'S.S. Aqua', name: 'Pokefan Colin', missable: true},
  { id: 239, location: 'S.S. Aqua', name: 'Twins Meg & Peg', missable: true},
  { id: 240, location: 'S.S. Aqua', name: 'Sailor Stanly', missable: true},
  { id: 241, location: 'S.S. Aqua', name: 'Juggler Fritz', missable: true},
  { id: 242, location: 'S.S. Aqua', name: 'Sailor Jeff', missable: true},
  { id: 243, location: 'S.S. Aqua', name: 'Picnicker Debra', missable: true},
  { id: 244, location: 'Vermilion City Gym', name: 'Guitarist Vincent', missable: true},
  { id: 245, location: 'Vermilion City Gym', name: 'Juggler Horton', missable: true},
  { id: 246, location: 'Vermilion City Gym', name: 'Gentleman Gregory', missable: true},
  { id: 247, location: 'Vermilion City Gym', name: 'Gym Leader Lt. Surge'},
  { id: 248, location: 'Saffron City Gym', name: 'Medium Rebecca', missable: true},
  { id: 249, location: 'Saffron City Gym', name: 'Psychic Franklin', missable: true},
  { id: 250, location: 'Saffron City Gym', name: 'Psychic Jared', missable: true},
  { id: 251, location: 'Saffron City Gym', name: 'Medium Doris', missable: true},
  { id: 252, location: 'Saffron City Gym', name: 'Gym Leader Sabrina'},
  { id: 253, location: 'Celadon City Gym', name: 'Twins Jo & Zoe'},
  { id: 254, location: 'Celadon City Gym', name: 'Lass Michelle', missable: true},
  { id: 255, location: 'Celadon City Gym', name: 'Picnicker Tanya', missable: true},
  { id: 256, location: 'Celadon City Gym', name: 'Beauty Julia'},
  { id: 257, location: 'Celadon City Gym', name: 'Gym Leader Erika'},
  { id: 258, location: 'Route 17', name: 'Biker Riley'},
  { id: 259, location: 'Route 17', name: 'Biker Glenn'},
  { id: 260, location: 'Route 17', name: 'Biker Joel'},
  { id: 261, location: 'Route 17', name: 'Biker Charles'},
  { id: 262, location: 'Route 18', name: 'Bird Keeper Bob'},
  { id: 263, location: 'Route 18', name: 'Bird Keeper Boris'},
  { id: 264, location: 'Fuschia City Gym', name: 'Lass Linda', missable: true},
  { id: 265, location: 'Fuschia City Gym', name: 'Picnicker Cindy', missable: true},
  { id: 266, location: 'Fuschia City Gym', name: 'Camper Barry', missable: true},
  { id: 267, location: 'Fuschia City Gym', name: 'Lass Alice', missable: true},
  { id: 268, location: 'Fuschia City Gym', name: 'Gym Leader Janine'},
  { id: 269, location: 'Route 9', name: 'Picnicker Edna'},
  { id: 270, location: 'Route 9', name: 'Camper Sid'},
  { id: 271, location: 'Route 9', name: 'Camper Dean'},
  { id: 272, location: 'Route 9', name: 'Hiker Sidney'},
  { id: 273, location: 'Route 9', name: 'Hiker Tim'},
  { id: 274, location: 'Route 9', name: 'Picnicker Heidi'},
  { id: 275, location: 'Route 24', name: 'Rocket Grunt', missable: true},
  { id: 276, location: 'Route 24', name: 'Schoolboy Dudley'},
  { id: 277, location: 'Route 24', name: 'Lass Ellen'},
  { id: 278, location: 'Route 25', name: 'Schoolboy Joe'},
  { id: 279, location: 'Route 25', name: 'Lass Laura'},
  { id: 280, location: 'Route 25', name: 'Camper Lloyd'},
  { id: 281, location: 'Route 25', name: 'Lass Shannon'},
  { id: 282, location: 'Route 25', name: 'Super Nerd Pat'},
  { id: 283, location: 'Route 25', name: 'Cooltrainer Kevin'},
  { id: 284, location: 'Cerulean City Gym', name: 'Swimmer♀ Brianna', missable: true},
  { id: 285, location: 'Cerulean City Gym', name: 'Swimmer♀ Parker', missable: true},
  { id: 286, location: 'Cerulean City Gym', name: 'Swimmer♀ Diana', missable: true},
  { id: 287, location: 'Cerulean City Gym', name: 'Gym Leader Misty'},
  { id: 288, location: 'Route 8', name: 'Biker Dwayne'},
  { id: 289, location: 'Route 8', name: 'Biker Harris'},
  { id: 290, location: 'Route 8', name: 'Biker Zeke'},
  { id: 291, location: 'Route 8', name: 'Super Nerd Sam'},
  { id: 292, location: 'Route 8', name: 'Super Nerd Tom'},
  { id: 293, location: 'Route 2', name: 'Bug Catcher Ed'},
  { id: 294, location: 'Pewter City Gym', name: 'Camper Jerry'},
  { id: 295, location: 'Pewter City Gym', name: 'Gym Leader Brock'},
  { id: 296, location: 'Route 2', name: 'Bug Catcher Doug'},
  { id: 297, location: 'Route 2', name: 'Bug Catcher Rob'},
  { id: 298, location: 'Route 21', name: 'Swimmer♀ Nikki'},
  { id: 299, location: 'Route 21', name: 'Fisher Arnold'},
  { id: 300, location: 'Route 21', name: 'Swimmer♂ Seth'},
  { id: 301, location: 'Route 20', name: 'Swimmer♂ Cameron'},
  { id: 302, location: 'Route 20', name: 'Swimmer♀ Lori'},
  { id: 303, location: 'Route 20', name: 'Swimmer♀ Nicole'},
  { id: 304, location: 'Seafoam Islands Gym', name: 'Gym Leader Blaine'},
  { id: 305, location: 'Viridian City Gym', name: 'Gym Leader Blue'},
  { id: 306, location: 'Route 3', name: 'Youngster Warren'},
  { id: 307, location: 'Route 3', name: 'Youngster Jimmy'},
  { id: 308, location: 'Route 3', name: 'Firebreather Otis'},
  { id: 309, location: 'Route 3', name: 'Firebreather Burt'},
  { id: 310, location: 'Mt. Moon', name: 'Rival Silver'},
  { id: 311, location: 'Route 4', name: 'Picnicker Hope'},
  { id: 312, location: 'Route 4', name: 'Bird Keeper Hawk'},
  { id: 313, location: 'Route 4', name: 'Picnicker Sharon'},
  { id: 314, location: 'Route 19', name: 'Swimmer♂ Jerome'},
  { id: 315, location: 'Route 19', name: 'Swimmer♀ Dawn'},
  { id: 316, location: 'Route 19', name: 'Swimmer♂ Tucker'},
  { id: 317, location: 'Route 19', name: 'Swimmer♂ Harold'},
  { id: 318, location: 'Route 10', name: 'Hiker Jim'},
  { id: 319, location: 'Route 10', name: 'Pokefan Robert'},
  { id: 320, location: 'Route 11', name: 'Psychic Fidel'},
  { id: 321, location: 'Route 11', name: 'Youngster Jason'},
  { id: 322, location: 'Route 11', name: 'Youngster Owen'},
  { id: 323, location: 'Route 11', name: 'Psychic Herman'},
  { id: 324, location: 'Route 12', name: 'Fisher Martin'},
  { id: 325, location: 'Route 12', name: 'Fisher Kyle'},
  { id: 326, location: 'Route 12', name: 'Fisher Stephen'},
  { id: 327, location: 'Route 12', name: 'Fisher Barney'},
  { id: 328, location: 'Route 13', name: 'Bird Keeper Bret'},
  { id: 329, location: 'Route 13', name: 'Bird Keeper Perry'},
  { id: 330, location: 'Route 13', name: 'Pokefan Joshua'},
  { id: 331, location: 'Route 13', name: 'Pokefan Alex'},
  { id: 332, location: 'Route 13', name: 'Hiker Kenny'},
  { id: 333, location: 'Route 14', name: 'Pokefan Carter'},
  { id: 334, location: 'Route 14', name: 'Bird Keeper Roy'},
  { id: 335, location: 'Route 15', name: 'Schoolboy Johnny'},
  { id: 336, location: 'Route 15', name: 'Teacher Colette'},
  { id: 337, location: 'Route 15', name: 'Schoolboy Billy'},
  { id: 338, location: 'Route 15', name: 'Teacher Hillary'},
  { id: 339, location: 'Route 15', name: 'Schoolboy Tommy'},
  { id: 340, location: 'Route 15', name: 'Schoolboy Kip'},
  { id: 341, location: 'Mount Silver', name: 'Pokemon Trainer Red'},
  { id: 342, location: 'Route 6', name: 'Pokefan Rex'},
  { id: 343, location: 'Route 6', name: 'Pokefan Allan'},
];

export default RIVALS;
